### ISSUE TITLE
Rewrite styles to use absolute path

### ISSUE THREAD

**Issue by josemarluedke** [jeffjewiss/ember-typeface#175]
First, thanks for this addon. It is awesome. 

So, I have a use case where I want to inline all my css into the html. I use [ember-inline-css](https://github.com/201-created/ember-inline-css) for that. 

The problem I encountered while using that addon with `ember-typeface` is that the css from the type face definition uses relative asset path as the following:

```
url('./files/open-sans-latin-300italic.woff2')
```

That works okay, when the css is been served under `/assets/`, but because of the inline css, that won't work.

For example, if I'm in the root of my page `/` the relative path would be `/files/open...`, while the correct path would be `/assets/files/open...`. This can also be a problem if I'm in a route like `/posts/yxz/`, so we would fetch the font from `/posts/yxy/files/open-sans....`. 

I believe one solution is to rewrite the urls (in the import step of `index.js`) to `/assets/files/` instead of leaving them as `./files/`.

**Comment by jeffjewiss** [comment]
Thanks for submitting this and sorry to hear it's not working for you right now.

I believe this add-on works in a slightly different way than you described, so one of the two problems you described should not be an issue.

The import: `this.import('node_modules/typeface-${typeface}/index.css...` ensures that this CSS file is included as part of your `vendor.css` so the relative path of the font files is actually relative to `assets/vendor.css`. This should mean that if you're on a route like `/posts/yxy/` the fonts should still work because they're relative to the CSS file and not the current route. They will also get fingerprinted by `assetRev` in production.

I can see why there will still be problem for the font face URLs as you described above. It should be possible to rewrite them in the import step using a transformation, similar to the AMD one built into `ember-cli` as seen here: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/transforms/amd/index.js

If you're able to put together a PR it would be much appreciated. Otherwise, I likely won't be able to get to this for at least a week.

Cheers
